### ISSUE TITLE
Calling packadd multiple times on FileType event

### ISSUE THREAD

**Issue by jmzagorski** [bennyyip/plugpac.vim#1]
Thanks for a great add-on to minpac. I had my own little add-on to minpac that only did lazy loading for filetypes, but I plan to trash mine and use yours since I liked the extra config options you have.

This is more of a question: Do you know if there is any performance penalty for calling `packadd` multiple times on the `FileType` event if the plugin is already loaded (for `type: opt` plugins)? https://github.com/bennyyip/plugpac.vim/blob/master/plugpac.vim#L48

**Comment by bennyyip** [comment]
Happy to see people use my plugin:)

According to https://vimhelp.org/repeat.txt.html, packadd adds plugin directory to rtp if it's not there yet. So the overhead of calling packadd multiple times is negligible.

**Comment by jmzagorski** [comment]
Thanks. I guess the only problem would be sourcing the plugin files over and over every time you open a new buffer with the same file type. The only way to stop that would be to check the runtimepath for the plugin name or it is up to the plugin author to check if their plugin was loaded, which many do (e.g  `if exists('g:plugin_loaded')` and is probably better.

**Comment by bennyyip** [comment]
> I guess the only problem would be sourcing the plugin files over and over every time you open a new buffer with the same file type.

This is how ftplugin works by design. So it's not a problem.

**Comment by jmzagorski** [comment]
I guess i was more concerned about the file under the plugin directory which normally only gets sourced once, but with adding `packadd` to the `FileType` event, it gets sourced every time like ftplugin. Most plugin authors do a good job to check if their plugin script was already sourced so my concern may not be that big of a deal. I can always add `match(&runtimepath, 'plugin-name') != -1` to the `FileType` event if i think something is slow with my plugins as a test

I will go ahead and close this since there is nothing to be done, and this was just a general question.
