### ISSUE TITLE
Usage unclear.

### ISSUE THREAD

**Issue by athendwyl** [bennyyip/plugpac.vim#4]
Very, noob question (am noob to Vim, but liking it thus far). Could you add a documentation section? Even just a basic list of commands/or usage instructions. I've tried reading the 'minpac' docs, but I am incredibly unfamiliar with the vimscript, and mapping them onto this is not somethinc I can really seem to get my head around. On top of that, I have absolutely 0 understanding of how to use the inbuilt package manager for Nvim, which, I'm going to assume _doesn't_ work the same way as this. Thank you!

**Comment by bennyyip** [comment]
I have updated document in README.md. Here is how I use plupac
https://github.com/bennyyip/dot-vim/blob/master/pack.vim

**Comment by Matthieu-Cordonnier** [comment]
Hello,
To use Plugpac, do my vimrc has to be written in vim9 script like your example?
Or will it work the same if my vimrc is legacy vim script ?

Best regards.
