### ISSUE TITLE
currently not working

### ISSUE THREAD

**Issue by jam1015** [bennyyip/plugpac.vim#5]
I follow the instructions both for legacy install and vim9 install and it is not working on my arch system, whereas it worked very nicely before.  Am on arch.

The reinstall looked like this: 

```
jmtp:~ > rm -rf ~/.vim/pack/minpac 
jmtp:~ > rm ~/.vim/autoload/plugpac.vim
jmtp:~ > git clone https://github.com/k-takata/minpac.git \
    ~/.vim/pack/minpac/opt/minpac
curl -fLo ~/.vim/autoload/plugpac.vim --create-dirs \
    https://raw.githubusercontent.com/bennyyip/plugpac.vim/master/plugpac.vim
```

**Comment by jam1015** [comment]
Noticed the breaking changes, `plugpac#Begin()` and `plugpac#End()` are now capitalized.

**Comment by jam1015** [comment]
might do a PR.

**Comment by bennyyip** [comment]
Sorry for breaking your config. Vim9 requires function name to be capitalized. 
It's documented in README.
